name: SDLC Lint All GitHub Actions
 
on:
  push:
    branches: ["main"]
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  pull_request:
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  workflow_dispatch:
 
jobs:
  lint-actions:
    uses: ERGO/sdlc-reusable-workflows/.github/workflows/sdlc-lint-github-workflows.yml@main